Tendermint integration
figment-networks/graph-node pull request #5
Opened 2021-12-15 18:38 UTC by pienkowb

2021-12-16 14:22 UTC, roignpar commented on chain/tendermint/src/hash.rs
> +}
@lukanus the `hash.rs` file is never used anywhere. is all this code needed?

2021-12-16 16:31 UTC, roignpar commented on chain/tendermint/src/trigger.rs
> +    pub event: codec::Event, // REVIEW: Do we want to have this behind an `Arc` wrapper?
IMO `Arc` shouldn't be used by default, only if it's needed. the compiler will definitely let us know if that will be the case after future changes.

2021-12-16 16:46 UTC, roignpar commented on chain/tendermint/src/types.rs
> +}
@lukanus `types.rs` is also not used anywhere. is it still needed?

2021-12-16 17:04 UTC, roignpar commented on graph/src/blockchain/types.rs
> +        let number = i32::try_from(number).unwrap();
is `number` guaranteed to always fit in `i32`?

2021-12-16 17:11 UTC, lukanus commented on chain/tendermint/src/hash.rs
> +}
I've placed this intialy for creation of cosmos-based addresses. It the data gets to the node correctly decoded (so you have cosmos addresses in cosmos and terra in terra) you can skip that @roignpar

2021-12-16 17:13 UTC, lukanus commented on graph/src/blockchain/types.rs
> +        let number = i32::try_from(number).unwrap();
@roignpar for this one you need to talk to @lavabyrd  :)

2021-12-16 17:15 UTC, lukanus commented on chain/tendermint/src/types.rs
> +}
@roignpar Not sure how about the latest version but it was used before :) as a node counterpart of ASC types

2021-12-17 19:17 UTC, pienkowb commented on chain/tendermint/src/hash.rs
> +}
This actually might be useful, I don't think we do any decoding on addresses right now.

2022-01-12 14:10 UTC, patiee requested changes

2022-01-12 14:10 UTC, patiee commented on server/index-node/src/resolver.rs
> -        response.insert("network".to_string(), network);
network is deleted from response intentionally?

2022-01-12 14:10 UTC, patiee commented on server/index-node/src/resolver.rs
> +        // TODO(Tendermint): check this type
block hash is correct right?

2022-01-14 14:37 UTC, roignpar commented on server/index-node/src/resolver.rs
> -        response.insert("network".to_string(), network);
i added this back in the origin merging/conflict resolving PR: https://github.com/figment-networks/graph-node/pull/7/files#diff-0238e3645398f2a041a40ad74876a35eff59db4b2f1a0bd6b6e795efc7997d25R267

2022-01-20 20:12 UTC, lavabyrd commented on chain/tendermint/src/runtime/abi.rs
> +            proposer_address: asc_new(heap, &Bytes(&self.proposer_address))?,
did we mean to drop the null here?

2022-01-20 20:14 UTC, lavabyrd commented on chain/tendermint/src/runtime/abi.rs
> +            validator_address: asc_new(heap, &Bytes(&self.validator_address))?,
again we've dropped the null. I just want to make sure its meant

2022-01-28 15:02 UTC, roignpar commented on chain/tendermint/src/types.rs
> +    //pub last_commit:  Option<TendermintCommit>,
removed the file, the entire module wasn't used

2022-01-28 15:02 UTC, roignpar commented on chain/tendermint/src/hash.rs
> +        //Hash::Sha256(ref h) =>
removed this file too, it wasn't used anywhere

2022-01-28 15:18 UTC, roignpar commented on server/index-node/src/resolver.rs
> +        // TODO(Tendermint): check this type
not sure, what do you mean by "correct"?

2022-01-28 15:28 UTC, roignpar commented on chain/tendermint/src/runtime/abi.rs
> +            proposer_address: asc_new(heap, &Bytes(&self.proposer_address))?,
`proposer_address` and `validator_address` both went from being `Option<Address>` to `Vec<u8>` as part of the proto definition changes @patiee made.

null was used when the value was `None`, but that can't happen anymore. the `Vec` can be empty, of course.

2022-02-02 12:33 UTC, lavabyrd commented on chain/tendermint/src/protobuf/gogoproto.rs
> +
I wonder do we still need these files btw? They seem to be empy

2022-02-02 12:33 UTC, lavabyrd commented on chain/tendermint/src/protobuf/google.protobuf.rs
> +
I wonder do we still need these files btw? They seem to be empy

2022-03-25 10:48 UTC, lavabyrd commented
Can we merge this or close it perhaps?

2022-03-25 11:01 UTC, closed without merging